behaviors:
  TagRunner:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 5128
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.15
      lambd: 0.9
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 32
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
  TagChaser:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 5128
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.15
      lambd: 0.9
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 32
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000
    time_horizon: 256
    summary_freq: 10000
    threaded: true